---
# tasks file for ansible-role-fpm

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

# - name: Create log directory
#   file:
#     path: "{{ fpm_log_dir }}"
#     mode: 0755
#     owner: "{{ fpm_user }}"
#     group: "{{ fpm_group }}"
#     state: directory
#   notify: Restart fpm
# 
# - name: Create db directory
#   file:
#     path: "{{ fpm_db_dir }}"
#     mode: 0755
#     owner: "{{ fpm_user }}"
#     group: "{{ fpm_group }}"
#     state: directory
#   notify: Restart fpm

- name: Create php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{ fpm_conf }}"
  notify: Restart fpm

- name: Start fpm
  service:
    name: "{{ fpm_service }}"
    enabled: true
    state: started
